import { StyleSheet } from 'react-native';

import type { ThemeColors } from '../theme';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 28,
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    header: {
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
      position: 'relative',
    },
    title: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '800',
      textAlign: 'center',
    },
    headerSettingsButton: {
      alignItems: 'center',
      bottom: 0,
      justifyContent: 'center',
      position: 'absolute',
      right: 0,
      top: 0,
      width: 36,
    },
    iconButton: {
      alignItems: 'center',
      height: 28,
      justifyContent: 'center',
      width: 28,
    },
    iconButtonText: {
      color: colors.subtleText,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 18,
    },
    errorText: {
      backgroundColor: colors.dangerSoft,
      borderRadius: 12,
      color: colors.danger,
      marginBottom: 12,
      padding: 12,
    },
    calendarCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      elevation: 2,
      overflow: 'hidden',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 20,
    },
    weekRow: {
      backgroundColor: colors.cardMuted,
      flexDirection: 'row',
      paddingVertical: 12,
    },
    weekDay: {
      color: colors.mutedText,
      flex: 1,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    daysGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    dayCell: {
      borderColor: colors.gridBorder,
      borderRightWidth: 1,
      borderTopWidth: 1,
      minHeight: 118,
      paddingBottom: 6,
      paddingTop: 6,
      width: `${100 / 7}%`,
    },
    outsideMonthDay: {
      backgroundColor: colors.background,
    },
    todayCell: {
      backgroundColor: colors.primarySoft,
    },
    dayHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 5,
      paddingHorizontal: 5,
    },
    dayNumber: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    outsideMonthText: {
      color: colors.subtleText,
    },
    todayText: {
      color: colors.primaryText,
    },
    memoCount: {
      backgroundColor: colors.stickyStrong,
      borderRadius: 999,
      color: colors.stickyText,
      fontSize: 10,
      fontWeight: '900',
      minWidth: 18,
      overflow: 'hidden',
      paddingHorizontal: 5,
      paddingVertical: 2,
      textAlign: 'center',
    },
    memoPreviewList: {
      gap: 4,
    },
    memoPreview: {
      backgroundColor: colors.sticky,
      borderLeftColor: colors.stickyStrong,
      borderLeftWidth: 2,
      borderRadius: 3,
      paddingHorizontal: 3,
      paddingVertical: 4,
    },
    memoPreviewText: {
      color: colors.stickyText,
      fontSize: 10,
      fontWeight: '700',
      lineHeight: 13,
    },
    pressed: {
      opacity: 0.72,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
    },
    stickyModalCard: {
      backgroundColor: colors.sticky,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      maxHeight: '88%',
      padding: 22,
      paddingBottom: 30,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: -8 },
      shadowOpacity: 0.16,
      shadowRadius: 20,
    },
    stickyTape: {
      alignSelf: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.55)',
      borderRadius: 6,
      height: 24,
      marginBottom: 8,
      width: 88,
    },
    modalTitle: {
      color: colors.stickyText,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 8,
    },
    modalDescription: {
      color: colors.stickyText,
      fontSize: 14,
      marginBottom: 14,
      opacity: 0.8,
    },
    memoList: {
      maxHeight: 250,
    },
    memoListContent: {
      gap: 10,
      paddingBottom: 8,
    },
    sectionTitle: {
      color: colors.stickyText,
      fontSize: 14,
      fontWeight: '900',
      marginBottom: 4,
    },
    emptyText: {
      color: colors.stickyText,
      fontSize: 15,
      opacity: 0.72,
      paddingVertical: 12,
    },
    memoListItem: {
      backgroundColor: 'rgba(255, 255, 255, 0.44)',
      borderColor: 'rgba(113, 63, 18, 0.18)',
      borderRadius: 14,
      borderWidth: 1,
      paddingBottom: 12,
      paddingLeft: 12,
      paddingRight: 38,
      paddingTop: 12,
    },
    memoListText: {
      color: colors.stickyText,
      fontSize: 15,
      fontWeight: '700',
      lineHeight: 21,
    },
    memoDeleteButton: {
      alignItems: 'center',
      height: 28,
      justifyContent: 'center',
      position: 'absolute',
      right: 7,
      top: 5,
      width: 28,
    },
    memoDeleteText: {
      color: colors.danger,
      fontSize: 22,
      fontWeight: '900',
      lineHeight: 22,
    },
    editorCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.34)',
      borderRadius: 18,
      marginTop: 12,
      padding: 12,
    },
    memoInput: {
      backgroundColor: 'rgba(255, 255, 255, 0.58)',
      borderColor: 'rgba(113, 63, 18, 0.2)',
      borderRadius: 14,
      borderWidth: 1,
      color: colors.stickyText,
      fontSize: 16,
      minHeight: 120,
      padding: 12,
    },
    modalActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 16,
    },
    secondaryButton: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.58)',
      borderRadius: 16,
      flex: 1,
      paddingVertical: 14,
    },
    secondaryButtonText: {
      color: colors.stickyText,
      fontSize: 16,
      fontWeight: '900',
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.stickyText,
      borderRadius: 16,
      flex: 1,
      paddingVertical: 14,
    },
    primaryButtonText: {
      color: colors.sticky,
      fontSize: 16,
      fontWeight: '900',
    },
    settingsScreen: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: 24,
    },
    settingsHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 24,
      paddingHorizontal: 24,
      paddingTop: 8,
    },
    settingsTitle: {
      color: colors.text,
      fontSize: 32,
      fontWeight: '900',
    },
    settingsCloseButton: {
      alignItems: 'center',
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    settingsScrollContent: {
      paddingBottom: 24,
      paddingHorizontal: 24,
    },
    authScrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingBottom: 32,
      paddingHorizontal: 24,
    },
    settingGroup: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      marginBottom: 16,
      padding: 18,
    },
    authCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      padding: 18,
    },
    settingLabel: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '900',
      marginBottom: 12,
    },
    settingActionRow: {
      flexDirection: 'row',
      gap: 10,
    },
    settingPrimaryAction: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 14,
      flex: 1,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    settingPrimaryActionText: {
      color: colors.background,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    settingSecondaryAction: {
      alignItems: 'center',
      backgroundColor: colors.cardMuted,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      flex: 1,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    settingSecondaryActionText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    dangerZone: {
      borderColor: colors.border,
      borderTopWidth: 1,
      marginTop: 16,
      paddingTop: 16,
    },
    settingDangerAction: {
      alignItems: 'center',
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
      borderRadius: 14,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    settingDangerActionText: {
      color: colors.danger,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    segmentedControl: {
      backgroundColor: colors.cardMuted,
      borderRadius: 16,
      flexDirection: 'row',
      gap: 6,
      padding: 5,
    },
    segmentButton: {
      alignItems: 'center',
      borderRadius: 12,
      flex: 1,
      minHeight: 44,
      justifyContent: 'center',
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    segmentButtonActive: {
      backgroundColor: colors.primary,
    },
    segmentButtonText: {
      color: colors.mutedText,
      fontSize: 15,
      fontWeight: '900',
    },
    segmentButtonTextActive: {
      color: colors.background,
    },
    accountHelpText: {
      color: colors.mutedText,
      fontSize: 13,
      lineHeight: 18,
      marginBottom: 14,
    },
    accountForm: {
      marginTop: 16,
    },
    accountFieldLabel: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '800',
      marginBottom: 6,
    },
    accountInput: {
      backgroundColor: colors.cardMuted,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      color: colors.text,
      fontSize: 16,
      marginBottom: 14,
      paddingHorizontal: 14,
      paddingVertical: 13,
    },
    accountError: {
      color: colors.danger,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 12,
    },
    accountPrimaryButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 14,
      minHeight: 52,
      justifyContent: 'center',
      paddingVertical: 14,
    },
    accountPrimaryButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: '900',
    },
    accountSignedInRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
    },
    accountEmailText: {
      color: colors.text,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '800',
    },
    accountSignOutButton: {
      alignItems: 'center',
      backgroundColor: colors.cardMuted,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      paddingHorizontal: 18,
      paddingVertical: 12,
    },
    accountSignOutButtonText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
    },
    accountInfoText: {
      color: colors.primaryText,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 12,
    },
    accountDivider: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
      marginTop: 18,
    },
    accountDividerLine: {
      backgroundColor: colors.border,
      flex: 1,
      height: 1,
    },
    accountDividerText: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    socialButtonStack: {
      gap: 10,
    },
    socialButton: {
      alignItems: 'center',
      borderRadius: 14,
      flexDirection: 'row',
      gap: 12,
      minHeight: 52,
      paddingHorizontal: 14,
      paddingVertical: 12,
      width: '100%',
    },
    socialButtonText: {
      flex: 1,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    socialIconPill: {
      alignItems: 'center',
      backgroundColor: 'rgba(15, 23, 42, 0.06)',
      borderRadius: 999,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    socialIconPillDark: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.16)',
      borderRadius: 999,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    socialIconPillKakao: {
      alignItems: 'center',
      backgroundColor: 'rgba(25, 22, 0, 0.1)',
      borderRadius: 999,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    socialGoogle: {
      backgroundColor: '#ffffff',
      borderColor: '#dadce0',
      borderWidth: 1,
    },
    socialGoogleText: {
      color: '#1f1f1f',
    },
    socialApple: {
      backgroundColor: '#000000',
    },
    socialAppleText: {
      color: '#ffffff',
    },
    socialKakao: {
      backgroundColor: '#FEE500',
    },
    socialKakaoText: {
      color: '#191600',
    },
  });

export type AppStyles = ReturnType<typeof createStyles>;
